# Generated by Django 5.1.6 on 2025-02-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('audio', models.FileField(upload_to='music/audio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
