# Generated by Django 5.1.6 on 2025-02-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='movie/image/')),
                ('video', models.FileField(upload_to='movie/video/')),
                ('release_date', models.DateField()),
            ],
        ),
    ]
